name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"
tasks = [ ]

[[processes]]
id = "hej3fnxl59vsjijfq9mo7xzt"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "x05b40j2cubdr57s2dta5xwz"
  title = "Opium backend"
  description = "get initial backend opium project built"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "qq328v17hn5b5t9wrasqd9xc"
  title = "Stage of completion"
  description = 'Need to setup a similar thing to the "to-do -> being done -> finished" aspect of kanban'
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "enqdyc585wbibx64r2uh9n7v"
  title = 'change status to drop down bar with "To Do", "In Progress" or "Done"'
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "mzg5nltyt8bbigjo2emaszhh"
  title = "create a CSS stylesheet"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "bzgxmc66a9ltzp53o5qoac1s"
  title = "Add buttons to navigate pages"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Low"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "aaqbjv4zxryynfy7uaik83xk"
  title = "Tasks"
  description = "Need to setup maybe a new struct that will hold: task name, task description, a priority, etc..."
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
