name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "cn90er5otygjuzl8inne1ef8"
  title = "Set up users"
  description = "Need to set up how we're going to track the names of people working on a project / working on tasks"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "aaqbjv4zxryynfy7uaik83xk"
  title = "Tasks"
  description = "Need to setup maybe a new struct that will hold: task name, task description, a priority, etc..."
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "qq328v17hn5b5t9wrasqd9xc"
  title = "Stage of completion"
  description = 'Need to setup a similar thing to the "to-do -> being done -> finished" aspect of kanban'
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "bzgxmc66a9ltzp53o5qoac1s"
  title = "Add buttons to navigate pages"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Low"
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"
tasks = [ ]
